### ISSUE TITLE
Support for development on Windows

### ISSUE THREAD

**Issue by akaustav** [js-fns/date-fns#3802] opened 2024-05-16 13:03 UTC
Is development on the Windows Operating System not supported?

As of commit [`c053552`](https://github.com/date-fns/date-fns/tree/c053552651f5354de6bd10cc20ea17a2cc9f7511) on the [`main`](https://github.com/date-fns/date-fns/tree/main) branch, when attempting to clone and build this library code on my Windows 11 machine (without WSL2 or any form of Linux involved), following the steps outlined under the [Getting Started](https://github.com/date-fns/date-fns/blob/main/CONTRIBUTING.md#getting-started) section within the [`CONTRIBUTING.md`](https://github.com/date-fns/date-fns/blob/main/CONTRIBUTING.md) file, I receive the following error on the `npm install` step:

```shell
C:\path\to\date-fns> npm i
npm error code EBADPLATFORM
npm error notsup Unsupported platform for bun@1.0.30: wanted {"os":"darwin,linux","cpu":"arm64,x64"} (current: {"os":"win32","cpu":"x64"}) 
npm error notsup Valid os:   darwin,linux
npm error notsup Actual os:  win32
npm error notsup Valid cpu:  arm64,x64
npm error notsup Actual cpu: x64

npm error A complete log of this run can be found in: C:\Users\<username>\AppData\Local\npm-cache\_logs\2024-05-16T12_57_07_869Z-debug-0.log
```

If it helps, here are some more details about my environment:

1. **Operating System** = Windows 11 Version 23H2 (OS Build 22631.3447)
2. **CPU Architecture** = 13th Gen Intel(R) Core(TM) i7-1365U 1.80 GHz
3. **Node.js version** = v22.1.0
4. **npm version** = 10.7.0

**Comment by fturmel** [comment] 2024-05-16 14:19
Dupe of #3785 and hopefully fixed in #3787 once it gets merged.

**Closed as completed** 2024-05-16 16:10 UTC
